[package]
name = "bergr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
aws-config = "1.8.11"
aws-sdk-s3 = "1.114.0"
clap = { version = "4.5.53", features = ["derive"] }
iceberg = "0.7.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
